version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

networks:
  my-network:
    driver: bridge

volumes:
  jenkins_home:
